### ISSUE TITLE
Build failure in serialport.c:353:22 error: CRTSCTS undeclared

### ISSUE THREAD

**Issue by gschmottlach** [tommie/esptool-ck#4]
FYI -

Under Ubuntu 14.04 (gcc 4.8.2) it fails to build due to CRTSCTS being undefined. This seems to be related to this issue:

http://stackoverflow.com/questions/26944217/crtscts-not-define-when-compiling-as-c99

My fix was to change the Makefile to specify -std=gnu99 instead of -std=c99. There are probably other solutions but this worked for me since I'm using a GNU tool-chain to build it.

**Comment by tommie** [comment]
Thanks for the report! Could you test current head?

I think gnu99 is not bad but excessive. It's just ensuring there is no RTS/CTS flow control enabled, and if libc doesn't provide the flag, we probably don't have it turned on anyway.

**Comment by gschmottlach** [comment]
I pulled it down and it compiled cleanly. Works like a champ now. Thanks for the quick fix.

Glenn
